# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      # All non-bat files should end with LF
      - id: mixed-line-ending
        name: Ensure LF endings on most files
        args: ["--fix=lf"]
        exclude: \.bat$
      # Bat files should end with CRLF
      - id: mixed-line-ending
        name: Ensure CRLF endings on Windows files
        args: ["--fix=crlf"]
        files: \.bat$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3

      - id: ruff-format
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.7.1 # The version to use or 'master' for latest
    hooks:
      - id: openapi-spec-validator
        files: ^api-spec/api-spec\.json$

  - repo: https://github.com/twu/skjold
    rev: v0.6.2
    hooks:
      - id: skjold
