#!/bin/bash

setup() {
    poetry install && \
    poetry run pre-commit install
}

lint() {
    poetry run pre-commit run --all-files
}

test() {
    poetry run pytest
}

autoupdate() {
    poetry update && \
    poetry run pre-commit autoupdate
}

case "$1" in
    setup)
        setup
        ;;
    lint)
        lint
        ;;
    test)
        test
        ;;
    autoupdate)
        autoupdate
        ;;
    *)
        echo "Error: Invalid command. Available commands: setup | lint | test | autoupdate"
        ;;
esac
