#!/bin/bash

setup() {
    poetry install && \
    poetry run pre-commit install
}

lint() {
    poetry run pre-commit run --all-files
}

test() {
    poetry run pytest --cov=finn_codesubmit --cov-report=xml --cov-report=term tests/
}

autoupdate() {
    poetry update && \
    poetry run pre-commit autoupdate
}

serve() {
    poetry run uvicorn finn_codesubmit.app:app --reload
}

case "$1" in
    setup)
        setup
        ;;
    lint)
        lint
        ;;
    test)
        test
        ;;
    autoupdate)
        autoupdate
        ;;
    serve)
        serve
        ;;
    *)
        echo "Error: Invalid command. Available commands: setup | lint | test | autoupdate | serve"
        ;;
esac
