org: psacc
app: project-serverless-app
service: project-service

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-python-requirements

functions:
  app:
    environment:
      URL_PREFIX: !GetAtt HttpApi.ApiEndpoint
      STAGE: ${self:provider.stage}
    handler: project.handler
    events:
      - httpApi: "*"

custom:
  pythonRequirements:
    usePoetry: true
